name: release

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  releaser:
    name: Release on GitHub
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Set up Go
        uses: actions/setup-go@v1.1.2
        with:
          go-version: 1.13.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}